[package]
authors = ["Sam Crow <samcrow@uw.edu>"]
name = "xplm"
version = "0.2.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/samcrow/rust-xplm"
keywords = ["X-Plane", "plugin"]
description = "High-level interfaces to the X-Plane plugin SDK"
readme = "README.md"

[dependencies]
lazy_static = "^0.2.1"
quick-error = "^1.1.0"
xplm-sys = "^0.2.1"

[[example]]
name = "dataref_test"
crate-type = ["cdylib"]

[[example]]
name = "basic_plugin"
crate-type = ["cdylib"]
